### ISSUE TITLE
Fix Deploy to IBM Cloud

### ISSUE THREAD

**Issue by ajbozarth** [IBM/MAX-Image-Caption-Generator-Web-App#24]
The Deploy to IBM Cloud section of the README had to be commented out due to an issue with the (assumed) product instance of the model endpoint. 

A production quality model endpoint needs to be determined and utilized before uncommenting the code. This production endpoint will be determined by the MAX dev team.

Note: This is blocking the "release" of v2 but not the publishing of the code pattern.

**Comment by rhagarty** [comment]
@ajbozarth couple issues with 'Deploy the Web App':
1) In Step 2, you should mention user needs to click on "Delivery Pipeline" to get to the option to enter the endpoint. 
2) Button is labeled "Create", not "Deploy". (I know, even the deploy panel instructions have it wrong!)
3) Not sure why, but previously we always needed to put "random-route: false" in our manifest so avoid getting the extra random string in our app URL. Maybe the default has changed? You should probably add it just to be sure. With "random", your URL would be too long.

**Comment by ajbozarth** [comment]
1. I noticed that something I did changed the default to the Git section rather than the Delivery Pipeline. I'll either fix it or make a note.
2. I'll fix that, it was wrong before so I didn't notice.
3. From my understanding that random string is important since it differentiate between different deployments of the app. I added the string myself in the toolchain (btw it's a timestamp)

**Comment by rhagarty** [comment]
3. You should test, but if you set it to "false", you should get a auto-generated timestamp appended to your name. But this may not be the case since you are using the new deploy mechanism.

**Comment by ajbozarth** [comment]
I know from experience while testing that without the numbers I can't deploy the app myself more than once (butI haven't tested that for different users). And that number you're seeing is an autogenerated timestamp.

**Comment by rhagarty** [comment]
yes, saw that in your toolchain.yml file. 

As I mentioned, we haven't used that before, so behavior must be different that what we've seen in the past. Thanks for explaining.

**Comment by ajbozarth** [comment]
When creating my lummox files I used these two repos for reference:
- https://github.com/open-toolchain/default-toolchain (this is the default that's used when you don't write your own files)
- https://github.com/IBM-Cloud/multiple-deployment-options (has examples of user imputed configs)

**Comment by ajbozarth** [comment]
@djalova opened #26 with the model deploy doc and I'll be opening #27 as a followup to that and this discussion in a moment
