### ISSUE TITLE
v2.0 Release

### ISSUE THREAD

**Issue by ajbozarth** [IBM/MAX-Image-Caption-Generator-Web-App#30]
@djalova @stevemart @rhagarty 

I've drafted a v2.0 release but want to double check with everyone and make sure there aren't anymore changes needed (don't want to cut a 2.1 for some missing text). Once I get the ok from each of you I'll cut the release on the current master. The idea is that this v2.0 cut would be the "final" change to the repo before moving on to our next code pattern. (not to say we wouldn't stay open to new ideas proposed once the pattern is published)

https://github.com/IBM/MAX-Image-Caption-Generator-Web-App/releases/tag/untagged-8e0ce32d39f6bb3a52f7

**Comment by stevemart** [comment]
@ajbozarth I'm good with this as is. Thank you for your detailed working/collaborating openly.

I'll let the others chime in.

**Comment by djalova** [comment]
👍

**Comment by rhagarty** [comment]
sounds good

**Comment by ajbozarth** [comment]
With unanimous approval I'll cut v2.0 on current master.
