### ISSUE TITLE
Create a wiki to draft IBMCode content

### ISSUE THREAD

**Issue by ajbozarth** [IBM/MAX-Image-Caption-Generator-Web-App#4]
Internal Requirements Doc:
https://pages.github.ibm.com/IBMCode/IBMCodeContent/patterns/dev/#2-create-a-wiki-to-draft-ibmcode-content

**Comment by stevemart** [comment]
Here's an example: https://github.com/IBM/powerai-counting-cars/wiki

**Comment by ajbozarth** [comment]
Made a couple updates to match current content. This task will most likely be the final task we are able to complete.

**Comment by ajbozarth** [comment]
Remaining wiki TODO:

- Update Intro Section

**Comment by ajbozarth** [comment]
@stevemart @rhagarty could you take a look at the wiki, other than adding a link to the video I believe it's complete

**Comment by stevemart** [comment]
@ajbozarth LGTM. I will close this issue and move this to the publishing team, stay tuned.
