### ISSUE TITLE
Image Caption Generator Model API Endpoint

### ISSUE THREAD

**Issue by joeljoseph17** [IBM/MAX-Image-Caption-Generator-Web-App#53]
I was following the tutorial and got lost on this point. "Fill in the Image Caption Generator Model API Endpoint section with the endpoint deployed above, then click on Create." Could you elaborate more?

**Comment by djalova** [comment]
This should refer to the endpoint you get from following the steps here:
https://github.com/IBM/MAX-Image-Caption-Generator-Web-App/blob/master/DEPLOY_MODEL.md

**Comment by joeljoseph17** [comment]
Awesome thanks @djalova
