### ISSUE TITLE
Create a video

### ISSUE THREAD

**Issue by ajbozarth** [IBM/MAX-Image-Caption-Generator-Web-App#8]
Internal Requirements Doc:
https://github.ibm.com/IBMCode/IBMCodeContent/blob/master/docs/patterns/dev/README.md#8-create-a-video

**Comment by ajbozarth** [comment]
Example videos for reference from Steve:
https://www.youtube.com/watch?v=Ynusw4RcyRY&t=6s&index=21&list=PLzUbsvIyrNfknNewObx5N7uGZ5FKH0Fde
https://www.youtube.com/watch?v=5EEmQwcjUa4&t=1s&index=25&list=PLzUbsvIyrNfknNewObx5N7uGZ5FKH0Fde
https://www.youtube.com/watch?v=MJUO0CLNbB0&t=11s&index=18&list=PLzUbsvIyrNfknNewObx5N7uGZ5FKH0Fde

Others:
https://www.youtube.com/playlist?list=PLzUbsvIyrNfknNewObx5N7uGZ5FKH0Fde

**Comment by ajbozarth** [comment]
Notes:
- Use Spark Summit video if possible.
- Use CODAIT YouTube channel.

Follow Up TODOs:
- Update REAME
- Update Wiki

**Comment by ajbozarth** [comment]
@stevemart @rhagarty The video we've been waiting on has finally been posted online, but the event organizers decided to use Vimeo instead of YouTube this year. Is it ok to imbed a Vimeo video?
https://vimeo.com/274936527

**Comment by stevemart** [comment]
Vimeo is OK. I still would have preferred a stand along type video that was 10 minutes or less from your point of view. But this is suitable. I hope I just didn't open Pandora's box and set a standard for people to use conference talks all the time. :/
