### ISSUE TITLE
Create a Blog

### ISSUE THREAD

**Issue by ajbozarth** [IBM/MAX-Image-Caption-Generator-Web-App#9]
Internal Requirements Doc:
https://github.ibm.com/IBMCode/IBMCodeContent/blob/master/docs/patterns/dev/README.md#9-create-a-blog

**Comment by ajbozarth** [comment]
Opened a blog contribution issue to start the process: 
https://github.ibm.com/IBMCode/IBMCodeContent/issues/939

**Comment by ajbozarth** [comment]
@stevemart as you suggested I'll use this issue for blog conversation. As for access I'm actually have editor privilege on IBMCode Blog already due to other projects. So I just need guidance on what process I should follow given I have the ability to both create and publish blogs already.

**Comment by stevemart** [comment]
@ajbozarth oh ok that makes things simpler :)

Just create a blog in IBMCode and save it as draft, enable public preview and insert that link in the wiki. An editor will look at that content when they review the whole pattern.

**Comment by ajbozarth** [comment]
Perfect, that's straight forward

**Comment by ajbozarth** [comment]
Blog in progress: https://developer.ibm.com/code/?p=38261&preview=true

**Comment by ajbozarth** [comment]
@stevemart @rhagarty @djalova My first draft of the blog is up if you would be kind enough to proofread and give feedback.
https://developer.ibm.com/code/?p=38261&preview=true

**Comment by ajbozarth** [comment]
@frreiss could you take a look at this as well?

**Comment by stevemart** [comment]
@ajbozarth make sure you clicked the option to enable public preview

**Comment by rhagarty** [comment]
@ajbozarth 

Content looks great!

Couple of small items...

Paragraph 1:
"... to scale their machine learning."  - seems like a word/concept is missing here. 

Paragraph 2:
"... how they were train" should be "how they were trained"

Paragraph 5:
"selected images with containing the word is selected" - "which contain the word are selected"

Paragraph 6:
"process user get a smoother" - "process the user gets a smoother"

Paragraph 7:
"The web UI also include" - "The web UI also includes"

**Comment by djalova** [comment]
@ajbozarth I can't access the post

**Comment by ajbozarth** [comment]
Enabled public preview @djalova @stevemart

**Comment by ajbozarth** [comment]
http://developer.ibm.com/code/?p=38261&preview=1&_ppp=a8d85847b7

**Comment by ajbozarth** [comment]
@rhagarty fixed your items, thanks

**Comment by stevemart** [comment]
@ajbozarth great blog!
